alias g='git status && gab'
alias giff='git diff'
alias gadd='git add'
alias getch='git fetch && g'
alias gull='git pull'
alias gush='git push'
alias geckout='git checkout'
alias gistash='git stash'
alias granch='git branch'
alias gommit='git commit'
alias glog='git log'
alias glean='git clean'

alias gipe='git diff HEAD --name-only | xargs '
alias gmod='gipe chmod -x && gipe ll'
alias gab='echo -ne "\033]0;$(basename `git rev-parse --show-toplevel`)\a"'
